# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_remind_before', models.TextField()),
                ('start_remind_from', models.TextField()),
                ('stop_in_moment', models.TextField()),
                ('remind_in', models.TextField()),
                ('datetimes', models.TextField()),
                ('interval', models.TextField()),
                ('weekdays', models.TextField()),
                ('parent', models.TextField()),
                ('kind', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('deadline', models.TextField()),
                ('priority', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=30)),
                ('subtasks', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='owners',
            field=models.ManyToManyField(to='nxtodo_db.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.Reminder'),
        ),
    ]
