# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owners',
        ),
        migrations.AddField(
            model_name='task',
            name='owners',
            field=models.TextField(default='owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.TextField(),
        ),
    ]
