# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0002_auto_20180516_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
