# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0003_auto_20180516_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='owners',
            field=models.TextField(default='owner', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.TextField(null=True),
        ),
    ]
