# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nxtodo_db', '0005_auto_20180516_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_remind_before', models.TextField()),
                ('start_remind_from', models.TextField()),
                ('stop_in_moment', models.TextField()),
                ('remind_in', models.TextField()),
                ('datetimes', models.TextField()),
                ('interval', models.TextField()),
                ('weekdays', models.TextField()),
                ('parent', models.TextField()),
                ('kind', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('reminder', models.TextField()),
                ('category', models.CharField(max_length=30, null=True)),
                ('owners', models.TextField(default='owner', null=True)),
                ('deadline', models.TextField(null=True)),
                ('priority', models.CharField(max_length=1, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('subtasks', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
