# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0008_reminder_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
