# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0013_auto_20180516_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('events', models.ManyToManyField(to='nxtodo_db.Event')),
                ('tasks', models.ManyToManyField(to='nxtodo_db.Task')),
            ],
        ),
    ]
