# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 09:34
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_remind_before', models.DurationField(null=True)),
                ('start_remind_from', models.DateTimeField(null=True)),
                ('remind_in', models.DurationField(null=True)),
                ('datetimes', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('interval', models.DurationField(null=True)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('datetimes_data', models.IntegerField(default=0)),
                ('interval_data', models.IntegerField(default=0)),
                ('weekdays_data', models.DateField(default=datetime.date(1, 1, 1))),
                ('remind_in_data', models.BooleanField(default=False)),
                ('right_now_data', models.BooleanField(default=False)),
                ('missed_data', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('deadline', models.TextField(null=True)),
                ('priority', models.CharField(max_length=1, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('subtasks', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('events', models.ManyToManyField(to='nxtodo_db.Event')),
                ('tasks', models.ManyToManyField(to='nxtodo_db.Task')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.Task'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.User'),
        ),
    ]
