# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='event',
        ),
    ]
