# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nxtodo_db', '0003_reminder_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.Event'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nxtodo_db.Task'),
        ),
    ]
