from .task_arguments import (
    TASK_ADD_ARGUMENTS,
    TASK_SHOW_ARGUMENTS,
    TASK_COMPLETE_ARGUMENTS,
    TASK_REMOVE_ARGUMENTS,
    TASK_CHECK_ARGUMENTS,
    TASK_EDIT_ARGUMENTS,
    TASK_SHARE_ARGUMENTS,
    TASK_UNSHARE_ARGUMENTS
)
from .event_arguments import (
    EVENT_ADD_ARGUMENTS,
    EVENT_SHOW_ARGUMENTS,
    EVENT_COMPLETE_ARGUMENTS,
    EVENT_REMOVE_ARGUMENTS,
    EVENT_CHECK_ARGUMENTS,
    EVENT_EDIT_ARGUMENTS,
    EVENT_SHARE_ARGUMENTS,
    EVENT_UNSHARE_ARGUMENTS
)
from .plan_arguments import (
    PLAN_ADD_ARGUMENTS,
    PLAN_SHOW_ARGUMENTS,
    PLAN_REMOVE_ARGUMENTS,
    PLAN_CHECK_ARGUMENTS,
    PLAN_EDIT_ARGUMENTS,
    PLAN_SHARE_ARGUMENTS,
    PLAN_UNSHARE_ARGUMENTS
)
from .reminder_arguments import (
    REMINDER_ADD_ARGUMENTS,
    REMINDER_SHOW_ARGUMENTS,
    REMINDER_REMOVE_ARGUMENTS,
    REMINDER_EDIT_ARGUMENTS,
)



TASK_COMMANDS = {
    'add': TASK_ADD_ARGUMENTS,
    'show': TASK_SHOW_ARGUMENTS,
    'complete': TASK_COMPLETE_ARGUMENTS,
    'remove': TASK_REMOVE_ARGUMENTS,
    'check': TASK_CHECK_ARGUMENTS,
    'edit': TASK_EDIT_ARGUMENTS,
    'share': TASK_SHARE_ARGUMENTS,
    'unshare': TASK_UNSHARE_ARGUMENTS
}


EVENT_COMMANDS = {
    'add': EVENT_ADD_ARGUMENTS,
    'show': EVENT_SHOW_ARGUMENTS,
    'complete': EVENT_COMPLETE_ARGUMENTS,
    'remove': EVENT_REMOVE_ARGUMENTS,
    'check': EVENT_CHECK_ARGUMENTS,
    'edit': EVENT_EDIT_ARGUMENTS,
    'share': EVENT_SHARE_ARGUMENTS,
    'unshare': EVENT_UNSHARE_ARGUMENTS
}

PLAN_COMMANDS = {
    'add': PLAN_ADD_ARGUMENTS,
    'show': PLAN_SHOW_ARGUMENTS,
    'remove': PLAN_REMOVE_ARGUMENTS,
    'check': PLAN_CHECK_ARGUMENTS,
    'edit': PLAN_EDIT_ARGUMENTS,
    'share': PLAN_SHARE_ARGUMENTS,
    'unshare': PLAN_UNSHARE_ARGUMENTS
}

REMINDER_COMMANDS = {
    'add': REMINDER_ADD_ARGUMENTS,
    'show': REMINDER_SHOW_ARGUMENTS,
    'remove': REMINDER_REMOVE_ARGUMENTS,
    'edit': REMINDER_EDIT_ARGUMENTS
}


ENTITIES = {
    'task': TASK_COMMANDS,
    'event': EVENT_COMMANDS,
    'plan': PLAN_COMMANDS,
    'reminder': REMINDER_COMMANDS
}
